In [2]:
from water_benchmark_hub.leakdb import LeakDB

db = LeakDB()

trial = db.load_scada_data(scenarios_id=[0], use_net1=False, download_dir="D:\LeakDB_full_data\Scada_Data_Full", return_X_y=True)

In [3]:
(type(trial), len(trial))

(list, 1)

In [4]:
arr = trial[0]
arr

(array([[  69.01888472,   56.83678977,   55.22968683, ..., -187.41014747,
          253.25157611,  725.47722561],
        [  69.1918904 ,   59.23020522,   57.92452207, ..., -166.84238569,
          228.89674842,  663.55640234],
        [  69.36395384,   61.5366649 ,   60.52442398, ..., -142.51467773,
          198.90529045,  540.14927628],
        ...,
        [  68.27689113,   46.9839314 ,   44.20923632, ..., -225.67368192,
          315.57481639,  961.34154713],
        [  68.59398766,   51.23113332,   49.08490555, ..., -225.99664829,
          293.60234933,  843.72558176],
        [  69.01888472,   56.83678977,   55.22968683, ..., -187.41014746,
          253.2515761 ,  725.4772256 ]]),
 array([0., 0., 0., ..., 0., 0., 0.]))

In [ ]:
import numpy as np
import pandas as pd

X, Y = arr[0], arr[1]
(len(X), len(Y))

(17521, 17521)

**In return_X_y, the result is a list, inside the list is another list, and inside that are X, and Y, so output -> [[[X], [Y]]]**

In [ ]:
# lets see for all scenarios

for i in range(1000):
    
    try:
        data = db.load_scada_data(scenarios_id=[i], use_net1=False, download_dir="D:\LeakDB_full_data\Scada_Data_Full", return_X_y=True)
        Y = data[0][1]
        print(f"Scenario-{i}: {np.unique(Y)}")
        
    except Exception as e:
        continue

Scenario-0: [0.]
Scenario-1: [0.]
Scenario-2: [0. 1.]
Scenario-3: [0. 1.]
Scenario-4: [0. 1.]
Scenario-5: [0.]
Scenario-6: [0. 1.]
Scenario-7: [0. 1.]
Scenario-8: [0. 1.]
Scenario-9: [0. 1.]
Scenario-10: [0.]
Scenario-11: [0. 1.]
Scenario-12: [0.]
Scenario-13: [0. 1.]
Scenario-14: [0.]
Scenario-15: [0. 1.]
Scenario-16: [0. 1.]
Scenario-17: [0. 1.]
Scenario-18: [0. 1.]
Scenario-19: [0. 1.]
Scenario-20: [0. 1.]
Scenario-21: [0. 1.]
Scenario-22: [0. 1.]
Scenario-23: [0. 1.]
Scenario-24: [0. 1.]
Scenario-25: [0. 1.]
Scenario-26: [0. 1.]
Scenario-27: [0.]
Scenario-28: [0.]
Scenario-29: [0.]
Scenario-30: [0. 1.]
Scenario-31: [0. 1.]
Scenario-32: [0. 1.]
Scenario-33: [0. 1.]
Scenario-34: [0. 1.]
Scenario-35: [0. 1.]
Scenario-36: [0. 1.]
Scenario-37: [0. 1.]
Scenario-38: [0. 1.]
Scenario-39: [0. 1.]
Scenario-40: [0. 1.]
Scenario-41: [0. 1.]
Scenario-42: [0. 1.]
Scenario-43: [0. 1.]
Scenario-44: [0.]
Scenario-45: [0. 1.]
Scenario-46: [0. 1.]
Scenario-47: [0. 1.]
Scenario-48: [0.]
Scenario-49: [

D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=501.epytflow_scada_data: 100%|##########| 13.2M/13.2M [00:23<00:00, 589kB/s] 


Scenario-501: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=502.epytflow_scada_data: 100%|##########| 13.2M/13.2M [00:17<00:00, 777kB/s] 


Scenario-502: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=503.epytflow_scada_data: 100%|##########| 13.2M/13.2M [02:42<00:00, 85.0kB/s]


Scenario-503: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=504.epytflow_scada_data: 100%|##########| 13.2M/13.2M [01:00<00:00, 228kB/s] 


Scenario-504: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=505.epytflow_scada_data: 100%|##########| 13.3M/13.3M [00:41<00:00, 331kB/s] 


Scenario-505: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=506.epytflow_scada_data: 100%|##########| 13.2M/13.2M [01:37<00:00, 142kB/s] 


Scenario-506: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=507.epytflow_scada_data: 100%|##########| 13.3M/13.3M [00:55<00:00, 249kB/s] 


Scenario-507: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=508.epytflow_scada_data: 100%|##########| 13.2M/13.2M [01:29<00:00, 156kB/s] 


Scenario-508: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=509.epytflow_scada_data: 100%|##########| 13.3M/13.3M [01:06<00:00, 208kB/s] 


Scenario-509: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=510.epytflow_scada_data: 100%|##########| 13.3M/13.3M [01:01<00:00, 227kB/s] 


Scenario-510: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=511.epytflow_scada_data: 100%|##########| 13.2M/13.2M [01:44<00:00, 133kB/s] 


Scenario-511: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=512.epytflow_scada_data: 100%|##########| 13.2M/13.2M [00:54<00:00, 255kB/s] 


Scenario-512: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=513.epytflow_scada_data: 100%|##########| 13.2M/13.2M [00:58<00:00, 239kB/s] 


Scenario-513: [0.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=514.epytflow_scada_data: 100%|##########| 13.3M/13.3M [01:16<00:00, 182kB/s] 


Scenario-514: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=515.epytflow_scada_data: 100%|##########| 13.3M/13.3M [00:50<00:00, 275kB/s] 


Scenario-515: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=516.epytflow_scada_data: 100%|##########| 13.2M/13.2M [01:08<00:00, 202kB/s] 


Scenario-516: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=517.epytflow_scada_data: 100%|##########| 13.3M/13.3M [01:24<00:00, 164kB/s] 


Scenario-517: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=518.epytflow_scada_data: 100%|##########| 13.2M/13.2M [01:51<00:00, 124kB/s] 


Scenario-518: [0. 1.]


D:\LeakDB_full_data\Scada_Data_Full\Hanoi_ID=519.epytflow_scada_data:  39%|###8      | 5.14M/13.3M [01:03<01:39, 85.3kB/s]


KeyboardInterrupt: 

In [5]:
location = db.load_scada_data(scenarios_id=[434], use_net1=False, download_dir="D:\LeakDB_full_data\Scada_Data_Full", return_X_y=True, return_leak_locations=True)
location

[(array([[  68.98989013,   49.31824479,   47.32295909, ..., -155.35482523,
           221.67153675,  698.23894876],
         [  69.21210011,   53.75021267,   52.18710651, ..., -118.91537092,
           178.79613527,  594.13506953],
         [  69.3517339 ,   56.67541756,   55.39868526, ..., -105.75886267,
           166.30280793,  532.28241796],
         ...,
         [  68.22069859,   33.76339064,   30.23745886, ..., -199.36843181,
           281.97067646,  978.07656179],
         [  68.5404306 ,   40.26108044,   37.4180771 , ..., -164.11367538,
           243.01961892,  865.45488134],
         [  68.98989013,   49.31824479,   47.32295909, ..., -155.35482523,
           221.67153675,  698.23894876]]),
  array([0., 0., 0., ..., 0., 0., 0.]),
  <Block Sparse Row sparse array of dtype 'float64'
  	with 4224 stored elements (blocksize=1x1) and shape (17521, 32)>)]

In [6]:
X = location[0][0]
Y = location[0][1]
loc = location[0][2]

In [ ]:
loc

<Block Sparse Row sparse array of dtype 'float64'
	with 4224 stored elements (blocksize=1x1) and shape (17521, 32)>

In [ ]:
loc.count_nonzero()

4224

In [ ]:
np.unique(loc)

array([<Block Sparse Row sparse array of dtype 'float64'
       	with 4224 stored elements (blocksize=1x1) and shape (17521, 32)>],
      dtype=object)

In [8]:
import pandas as pd
loc_df = pd.DataFrame(loc.toarray())

In [ ]:
loc_df.head(10)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0


In [ ]:
loc_df.columns

RangeIndex(start=0, stop=32, step=1)

In [ ]:
for i in range(32):
    print(f"node {i}: {loc_df[i].unique()}")

node 0: [0.]
node 1: [0.]
node 2: [0.]
node 3: [0.]
node 4: [0.]
node 5: [0.]
node 6: [0.]
node 7: [0.]
node 8: [0.]
node 9: [0.]
node 10: [0.]
node 11: [0.]
node 12: [0.]
node 13: [0.]
node 14: [0.]
node 15: [0.]
node 16: [0.]
node 17: [0.]
node 18: [0.]
node 19: [0.]
node 20: [0.]
node 21: [0.]
node 22: [0.]
node 23: [0.]
node 24: [0.]
node 25: [0. 1.]
node 26: [0.]
node 27: [0.]
node 28: [0.]
node 29: [0.]
node 30: [0.]
node 31: [0.]


In [ ]:
loc_df[25].value_counts()

25
0.0    13297
1.0     4224
Name: count, dtype: int64

**So what can be done is to find which scenarios have leakages, out of those that have, find which nodes have and then find what if the count of the leakages.**

In [9]:
loc_df[25].sum()

4224.0